# -*- coding: utf-8 -*-
# ACADEMIC arm query table, protocol_kalshi-strategy-multivocal_2026-09-04.md section 3.1.
# Each query = (i) one instrument term AND (ii) one strategy term AND (iii) optional venue narrowing.
# No date filter, no language filter. Field restriction to title-and-abstract where offered.
#
# No PYTHONHASHSEED assert here, deliberately: this module is a pure data table. It defines
# four literal constants and one explicitly ordered list, executes no set or dict iteration,
# and writes nothing, so it has no hash-order dependence for a seed to pin. Every module that
# CONSUMES this table (ks-academic-runner.py, ks-academic-recovery-pass.py,
# ks-academic-query-table-supplementary.py) asserts PYTHONHASHSEED=0 at its own entry.
#
# The archived filename is hyphenated and therefore not importable; its importers use the
# module name `queries`. See queries.py in this directory, and README.md.
CROSSREF_SEL = "&rows=20&select=DOI,title,issued,container-title,type,author,abstract"
CR = "https://api.crossref.org/works?query.bibliographic="
OA_MAIL = "&mailto=238704148%2Bs-koirala%40users.noreply.github.com"

QUERIES = [
 # ---------------- Crossref (rows=20) ----------------
 dict(qid="ks-crossref-01", platform="crossref", stratum="S1-venue-and-contract-families",
      instrument="event contract", strategy="execution", venue="Kalshi", cap="rows=20",
      url=CR+"Kalshi+event+contract+execution"+CROSSREF_SEL),
 dict(qid="ks-crossref-02", platform="crossref", stratum="S1-venue-and-contract-families",
      instrument="binary event contract", strategy="market making", venue=None, cap="rows=20",
      url=CR+"binary+event+contract+market+making"+CROSSREF_SEL),
 dict(qid="ks-crossref-03", platform="crossref", stratum="S6-regulated-DCM-microstructure",
      instrument="event contract", strategy="inventory", venue="designated contract market", cap="rows=20",
      url=CR+"designated+contract+market+event+contract+inventory"+CROSSREF_SEL),
 dict(qid="ks-crossref-04", platform="crossref", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="prediction market", strategy="arbitrage", venue="sportsbook", cap="rows=20",
      url=CR+"sportsbook+prediction+market+arbitrage"+CROSSREF_SEL),
 dict(qid="ks-crossref-05", platform="crossref", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="sports event contract", strategy="mispricing", venue=None, cap="rows=20",
      url=CR+"sports+event+contract+mispricing"+CROSSREF_SEL),
 dict(qid="ks-crossref-06", platform="crossref", stratum="S3-weather-and-climate-event-contracts",
      instrument="weather event contract", strategy="hedging", venue=None, cap="rows=20",
      url=CR+"weather+event+contract+hedging"+CROSSREF_SEL),
 dict(qid="ks-crossref-07", platform="crossref", stratum="S3-weather-and-climate-event-contracts",
      instrument="temperature precipitation event contract", strategy="arbitrage", venue=None, cap="rows=20",
      url=CR+"temperature+precipitation+event+contract+settlement+arbitrage"+CROSSREF_SEL),
 dict(qid="ks-crossref-08", platform="crossref", stratum="S4-macro-event-contracts",
      instrument="economic event contract", strategy="hedging", venue="CME fed funds futures", cap="rows=20",
      url=CR+"economic+event+contract+hedging+CME+fed+funds+futures"+CROSSREF_SEL),
 dict(qid="ks-crossref-09", platform="crossref", stratum="S4-macro-event-contracts",
      instrument="inflation CPI event contract", strategy="mispricing", venue=None, cap="rows=20",
      url=CR+"inflation+CPI+event+contract+mispricing"+CROSSREF_SEL),
 dict(qid="ks-crossref-10", platform="crossref", stratum="S5-cross-venue",
      instrument="Kalshi Polymarket PredictIt", strategy="arbitrage", venue=None, cap="rows=20",
      url=CR+"Kalshi+Polymarket+PredictIt+cross+venue+arbitrage"+CROSSREF_SEL),
 dict(qid="ks-crossref-11", platform="crossref", stratum="S6-regulated-DCM-microstructure",
      instrument="binary event contract", strategy="quoting", venue=None, cap="rows=20",
      url=CR+"binary+event+contract+quoting+collateral+capital+efficiency"+CROSSREF_SEL),
 dict(qid="ks-crossref-12", platform="crossref", stratum="S7-LLM-and-forecasting-driven-trading",
      instrument="prediction market", strategy="forecasting-driven trading", venue=None, cap="rows=20",
      url=CR+"prediction+market+forecasting+driven+trading+agent"+CROSSREF_SEL),
 dict(qid="ks-crossref-13", platform="crossref", stratum="S5-cross-venue",
      instrument="Betfair Iowa Electronic Markets event contract", strategy="coherence", venue=None, cap="rows=20",
      url=CR+"Betfair+Iowa+Electronic+Markets+event+contract+coherence"+CROSSREF_SEL),
 dict(qid="ks-crossref-14", platform="crossref", stratum="S1-venue-and-contract-families",
      instrument="event contract", strategy="market making", venue="SSRN container narrowing", cap="rows=20",
      note=("SSRN's own search interface returns HTTP 403 unauthenticated (logged as ks-ssrn-01), so the SSRN "
            "portion of this arm's platform list is executed through Crossref's container-title field. This is a "
            "container narrowing, not a subject narrowing; reason recorded per section 3.1."),
      url=CR+"Kalshi+event+contract+market+making+arbitrage&query.container-title=SSRN"+CROSSREF_SEL),
 dict(qid="ks-crossref-15", platform="crossref", stratum="S4-macro-event-contracts",
      instrument="event contract", strategy="hedging", venue="government shutdown payrolls GDP", cap="rows=20",
      url=CR+"event+contract+hedging+government+shutdown+payrolls+GDP+macroeconomic+announcement"+CROSSREF_SEL),

 # ---------------- OpenAlex (per-page=25) ----------------
 dict(qid="ks-openalex-01", platform="openalex", stratum="S1-venue-and-contract-families",
      instrument="event contract", strategy="market making", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22event%20contract%22%20AND%20%22market%20making%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-02", platform="openalex", stratum="S1-venue-and-contract-families",
      instrument="Kalshi", strategy="arbitrage", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22Kalshi%22%20AND%20%22arbitrage%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-03", platform="openalex", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="sports betting exchange", strategy="arbitrage", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22sports%20betting%22%20AND%20%22arbitrage%22%20AND%20%22exchange%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-04", platform="openalex", stratum="S3-weather-and-climate-event-contracts",
      instrument="weather event contract", strategy="hedging", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22weather%22%20AND%20%22event%20contract%22%20AND%20%22hedging%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-05", platform="openalex", stratum="S4-macro-event-contracts",
      instrument="prediction market", strategy="hedging", venue="macroeconomic announcement", cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22prediction%20market%22%20AND%20%22macroeconomic%22%20AND%20%22hedging%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-06", platform="openalex", stratum="S5-cross-venue",
      instrument="Polymarket PredictIt", strategy="arbitrage", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22Polymarket%22%20AND%20%22arbitrage%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-07", platform="openalex", stratum="S6-regulated-DCM-microstructure",
      instrument="binary contract", strategy="spread", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22binary%20contract%22%20AND%20%22bid-ask%20spread%22&per-page=25'+OA_MAIL),
 dict(qid="ks-openalex-08", platform="openalex", stratum="S7-LLM-and-forecasting-driven-trading",
      instrument="prediction market", strategy="forecasting-driven trading", venue=None, cap="per-page=25",
      url='https://api.openalex.org/works?filter=title_and_abstract.search:%22prediction%20market%22%20AND%20%22forecasting%22%20AND%20%22trading%22&per-page=25'+OA_MAIL),

 # ---------------- arXiv (max_results=50) ----------------
 dict(qid="ks-arxiv-01", platform="arxiv", stratum="S1-venue-and-contract-families",
      instrument="event contract", strategy="market making", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22event%20contract%22%20AND%20abs:%22market%20making%22&max_results=50'),
 dict(qid="ks-arxiv-02", platform="arxiv", stratum="S1-venue-and-contract-families",
      instrument="Kalshi", strategy="arbitrage", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22Kalshi%22%20AND%20abs:%22arbitrage%22&max_results=50'),
 dict(qid="ks-arxiv-03", platform="arxiv", stratum="S7-LLM-and-forecasting-driven-trading",
      instrument="prediction market", strategy="forecasting-driven trading", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22prediction%20market%22%20AND%20abs:%22forecasting%22&max_results=50'),
 dict(qid="ks-arxiv-04", platform="arxiv", stratum="S3-weather-and-climate-event-contracts,S4-macro-event-contracts",
      instrument="event contract", strategy="hedging", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22event%20contract%22%20AND%20abs:%22hedging%22&max_results=50'),
 dict(qid="ks-arxiv-05", platform="arxiv", stratum="S6-regulated-DCM-microstructure",
      instrument="event contract", strategy="inventory", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22event%20contract%22%20AND%20abs:%22inventory%22&max_results=50'),
 dict(qid="ks-arxiv-06", platform="arxiv", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="betting exchange", strategy="execution", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22betting%20exchange%22%20AND%20abs:%22execution%22&max_results=50'),
 dict(qid="ks-arxiv-07", platform="arxiv", stratum="S5-cross-venue",
      instrument="Polymarket", strategy="arbitrage", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22Polymarket%22%20AND%20abs:%22arbitrage%22&max_results=50'),
 dict(qid="ks-arxiv-08", platform="arxiv", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="sports betting market", strategy="mispricing", venue=None, cap="max_results=50",
      url='https://export.arxiv.org/api/query?search_query=abs:%22sports%20betting%22%20AND%20abs:%22mispricing%22&max_results=50'),

 # ---------------- Semantic Scholar (limit=50) ----------------
 dict(qid="ks-s2-01", platform="semanticscholar", stratum="S1-venue-and-contract-families",
      instrument="Kalshi event contract", strategy="market making", venue=None, cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=Kalshi%20event%20contract%20market%20making&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),
 dict(qid="ks-s2-02", platform="semanticscholar", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="event contract", strategy="arbitrage", venue="sportsbook betting exchange", cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=sportsbook%20betting%20exchange%20arbitrage%20event%20contract&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),
 dict(qid="ks-s2-03", platform="semanticscholar", stratum="S3-weather-and-climate-event-contracts",
      instrument="weather event contract", strategy="hedging", venue=None, cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=weather%20event%20contract%20temperature%20settlement%20hedging&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),
 dict(qid="ks-s2-04", platform="semanticscholar", stratum="S4-macro-event-contracts",
      instrument="economic event contract", strategy="mispricing", venue=None, cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=macroeconomic%20announcement%20event%20contract%20prediction%20market%20mispricing&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),
 dict(qid="ks-s2-05", platform="semanticscholar", stratum="S7-LLM-and-forecasting-driven-trading",
      instrument="prediction market", strategy="forecasting-driven trading", venue=None, cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=language%20model%20agent%20prediction%20market%20forecasting%20trading&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),
 dict(qid="ks-s2-06", platform="semanticscholar", stratum="S6-regulated-DCM-microstructure",
      instrument="binary event contract", strategy="spread", venue="regulated exchange", cap="limit=50",
      url='https://api.semanticscholar.org/graph/v1/paper/search?query=regulated%20exchange%20binary%20event%20contract%20collateral%20capital%20efficiency%20spread&fields=title,year,venue,externalIds,abstract,citationCount,publicationTypes&limit=50'),

 # ---------------- RePEc / IDEAS ----------------
 dict(qid="ks-repec-01", platform="repec", stratum="S1-venue-and-contract-families",
      instrument="event contract", strategy="market making", venue="Kalshi", cap="platform offers no cap parameter; platform default page size in force",
      url='https://ideas.repec.org/cgi-bin/htsearch?q=Kalshi+event+contract+market+making'),
 dict(qid="ks-repec-02", platform="repec", stratum="S2-sports-and-sportsbook-vs-exchange",
      instrument="event contract", strategy="arbitrage", venue="sportsbook betting exchange", cap="platform offers no cap parameter; platform default page size in force",
      url='https://ideas.repec.org/cgi-bin/htsearch?q=sportsbook+betting+exchange+arbitrage+event+contract'),
 dict(qid="ks-repec-03", platform="repec", stratum="S4-macro-event-contracts",
      instrument="macroeconomic event contract", strategy="hedging", venue=None, cap="platform offers no cap parameter; platform default page size in force",
      url='https://ideas.repec.org/cgi-bin/htsearch?q=macroeconomic+event+contract+prediction+market+hedging'),
 dict(qid="ks-repec-04", platform="repec", stratum="S3-weather-and-climate-event-contracts",
      instrument="weather event contract", strategy="hedging", venue=None, cap="platform offers no cap parameter; platform default page size in force",
      url='https://ideas.repec.org/cgi-bin/htsearch?q=weather+event+contract+temperature+hedging+prediction+market'),

 # ---------------- SSRN reachability probe ----------------
 dict(qid="ks-ssrn-01", platform="ssrn", stratum="platform-reachability-probe",
      instrument="event contract", strategy="arbitrage", venue="Kalshi", cap="not applicable; the platform returned an error before any retrieval cap could bind",
      url='https://papers.ssrn.com/sol3/results.cfm?txtKey_Words=Kalshi+event+contract+arbitrage'),
]
